
package sn.gestion.notes.service.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import sn.gestion.notes.service.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NotesWebService", targetNamespace = "http://service.notes.gestion.sn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NotesWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rang", targetNamespace = "http://service.notes.gestion.sn/", className = "sn.gestion.notes.service.Rang")
    @ResponseWrapper(localName = "rangResponse", targetNamespace = "http://service.notes.gestion.sn/", className = "sn.gestion.notes.service.RangResponse")
    @Action(input = "http://service.notes.gestion.sn/NotesWebService/rangRequest", output = "http://service.notes.gestion.sn/NotesWebService/rangResponse")
    public int rang(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "moyenne", targetNamespace = "http://service.notes.gestion.sn/", className = "sn.gestion.notes.service.Moyenne")
    @ResponseWrapper(localName = "moyenneResponse", targetNamespace = "http://service.notes.gestion.sn/", className = "sn.gestion.notes.service.MoyenneResponse")
    @Action(input = "http://service.notes.gestion.sn/NotesWebService/moyenneRequest", output = "http://service.notes.gestion.sn/NotesWebService/moyenneResponse")
    public double moyenne(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Integer> arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "nomComplet", targetNamespace = "http://service.notes.gestion.sn/", className = "sn.gestion.notes.service.NomComplet")
    @ResponseWrapper(localName = "nomCompletResponse", targetNamespace = "http://service.notes.gestion.sn/", className = "sn.gestion.notes.service.NomCompletResponse")
    @Action(input = "http://service.notes.gestion.sn/NotesWebService/nomCompletRequest", output = "http://service.notes.gestion.sn/NotesWebService/nomCompletResponse")
    public String nomComplet(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
